name: Django CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['backend']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11.9]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Debug Directory Structure
        run: |
          pwd  # Print working directory
          ls -R  # List all files and folders recursively
          find . -name "manage.py"  # Find the location of manage.py

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        working-directory: easylist-backend
        run: |
          python manage.py test
